/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DeveloperToolProficiencyService } from "../developerToolProficiency.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeveloperToolProficiencyCreateInput } from "./DeveloperToolProficiencyCreateInput";
import { DeveloperToolProficiency } from "./DeveloperToolProficiency";
import { DeveloperToolProficiencyFindManyArgs } from "./DeveloperToolProficiencyFindManyArgs";
import { DeveloperToolProficiencyWhereUniqueInput } from "./DeveloperToolProficiencyWhereUniqueInput";
import { DeveloperToolProficiencyUpdateInput } from "./DeveloperToolProficiencyUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DeveloperToolProficiencyControllerBase {
  constructor(
    protected readonly service: DeveloperToolProficiencyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DeveloperToolProficiency })
  @nestAccessControl.UseRoles({
    resource: "DeveloperToolProficiency",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDeveloperToolProficiency(
    @common.Body() data: DeveloperToolProficiencyCreateInput
  ): Promise<DeveloperToolProficiency> {
    return await this.service.createDeveloperToolProficiency({
      data: {
        ...data,

        developer: data.developer
          ? {
              connect: data.developer,
            }
          : undefined,

        proficiencyLevel: data.proficiencyLevel
          ? {
              connect: data.proficiencyLevel,
            }
          : undefined,

        tool: data.tool
          ? {
              connect: data.tool,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        developer: {
          select: {
            id: true,
          },
        },

        id: true,

        proficiencyLevel: {
          select: {
            id: true,
          },
        },

        tool: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DeveloperToolProficiency] })
  @ApiNestedQuery(DeveloperToolProficiencyFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DeveloperToolProficiency",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async developerToolProficiencies(
    @common.Req() request: Request
  ): Promise<DeveloperToolProficiency[]> {
    const args = plainToClass(
      DeveloperToolProficiencyFindManyArgs,
      request.query
    );
    return this.service.developerToolProficiencies({
      ...args,
      select: {
        createdAt: true,

        developer: {
          select: {
            id: true,
          },
        },

        id: true,

        proficiencyLevel: {
          select: {
            id: true,
          },
        },

        tool: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DeveloperToolProficiency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DeveloperToolProficiency",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async developerToolProficiency(
    @common.Param() params: DeveloperToolProficiencyWhereUniqueInput
  ): Promise<DeveloperToolProficiency | null> {
    const result = await this.service.developerToolProficiency({
      where: params,
      select: {
        createdAt: true,

        developer: {
          select: {
            id: true,
          },
        },

        id: true,

        proficiencyLevel: {
          select: {
            id: true,
          },
        },

        tool: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DeveloperToolProficiency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DeveloperToolProficiency",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDeveloperToolProficiency(
    @common.Param() params: DeveloperToolProficiencyWhereUniqueInput,
    @common.Body() data: DeveloperToolProficiencyUpdateInput
  ): Promise<DeveloperToolProficiency | null> {
    try {
      return await this.service.updateDeveloperToolProficiency({
        where: params,
        data: {
          ...data,

          developer: data.developer
            ? {
                connect: data.developer,
              }
            : undefined,

          proficiencyLevel: data.proficiencyLevel
            ? {
                connect: data.proficiencyLevel,
              }
            : undefined,

          tool: data.tool
            ? {
                connect: data.tool,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          developer: {
            select: {
              id: true,
            },
          },

          id: true,

          proficiencyLevel: {
            select: {
              id: true,
            },
          },

          tool: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DeveloperToolProficiency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DeveloperToolProficiency",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDeveloperToolProficiency(
    @common.Param() params: DeveloperToolProficiencyWhereUniqueInput
  ): Promise<DeveloperToolProficiency | null> {
    try {
      return await this.service.deleteDeveloperToolProficiency({
        where: params,
        select: {
          createdAt: true,

          developer: {
            select: {
              id: true,
            },
          },

          id: true,

          proficiencyLevel: {
            select: {
              id: true,
            },
          },

          tool: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
