/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProficiencyLevelService } from "../proficiencyLevel.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProficiencyLevelCreateInput } from "./ProficiencyLevelCreateInput";
import { ProficiencyLevel } from "./ProficiencyLevel";
import { ProficiencyLevelFindManyArgs } from "./ProficiencyLevelFindManyArgs";
import { ProficiencyLevelWhereUniqueInput } from "./ProficiencyLevelWhereUniqueInput";
import { ProficiencyLevelUpdateInput } from "./ProficiencyLevelUpdateInput";
import { DeveloperToolProficiencyFindManyArgs } from "../../developerToolProficiency/base/DeveloperToolProficiencyFindManyArgs";
import { DeveloperToolProficiency } from "../../developerToolProficiency/base/DeveloperToolProficiency";
import { DeveloperToolProficiencyWhereUniqueInput } from "../../developerToolProficiency/base/DeveloperToolProficiencyWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProficiencyLevelControllerBase {
  constructor(
    protected readonly service: ProficiencyLevelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProficiencyLevel })
  @nestAccessControl.UseRoles({
    resource: "ProficiencyLevel",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createProficiencyLevel(
    @common.Body() data: ProficiencyLevelCreateInput
  ): Promise<ProficiencyLevel> {
    return await this.service.createProficiencyLevel({
      data: data,
      select: {
        createdAt: true,
        id: true,
        levelName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ProficiencyLevel] })
  @ApiNestedQuery(ProficiencyLevelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProficiencyLevel",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async proficiencyLevels(
    @common.Req() request: Request
  ): Promise<ProficiencyLevel[]> {
    const args = plainToClass(ProficiencyLevelFindManyArgs, request.query);
    return this.service.proficiencyLevels({
      ...args,
      select: {
        createdAt: true,
        id: true,
        levelName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProficiencyLevel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProficiencyLevel",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async proficiencyLevel(
    @common.Param() params: ProficiencyLevelWhereUniqueInput
  ): Promise<ProficiencyLevel | null> {
    const result = await this.service.proficiencyLevel({
      where: params,
      select: {
        createdAt: true,
        id: true,
        levelName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProficiencyLevel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProficiencyLevel",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateProficiencyLevel(
    @common.Param() params: ProficiencyLevelWhereUniqueInput,
    @common.Body() data: ProficiencyLevelUpdateInput
  ): Promise<ProficiencyLevel | null> {
    try {
      return await this.service.updateProficiencyLevel({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          levelName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProficiencyLevel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProficiencyLevel",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProficiencyLevel(
    @common.Param() params: ProficiencyLevelWhereUniqueInput
  ): Promise<ProficiencyLevel | null> {
    try {
      return await this.service.deleteProficiencyLevel({
        where: params,
        select: {
          createdAt: true,
          id: true,
          levelName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/developerToolProficiencies")
  @ApiNestedQuery(DeveloperToolProficiencyFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DeveloperToolProficiency",
    action: "read",
    possession: "any",
  })
  async findDeveloperToolProficiencies(
    @common.Req() request: Request,
    @common.Param() params: ProficiencyLevelWhereUniqueInput
  ): Promise<DeveloperToolProficiency[]> {
    const query = plainToClass(
      DeveloperToolProficiencyFindManyArgs,
      request.query
    );
    const results = await this.service.findDeveloperToolProficiencies(
      params.id,
      {
        ...query,
        select: {
          createdAt: true,

          developer: {
            select: {
              id: true,
            },
          },

          id: true,

          proficiencyLevel: {
            select: {
              id: true,
            },
          },

          tool: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      }
    );
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/developerToolProficiencies")
  @nestAccessControl.UseRoles({
    resource: "ProficiencyLevel",
    action: "update",
    possession: "any",
  })
  async connectDeveloperToolProficiencies(
    @common.Param() params: ProficiencyLevelWhereUniqueInput,
    @common.Body() body: DeveloperToolProficiencyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      developerToolProficiencies: {
        connect: body,
      },
    };
    await this.service.updateProficiencyLevel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/developerToolProficiencies")
  @nestAccessControl.UseRoles({
    resource: "ProficiencyLevel",
    action: "update",
    possession: "any",
  })
  async updateDeveloperToolProficiencies(
    @common.Param() params: ProficiencyLevelWhereUniqueInput,
    @common.Body() body: DeveloperToolProficiencyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      developerToolProficiencies: {
        set: body,
      },
    };
    await this.service.updateProficiencyLevel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/developerToolProficiencies")
  @nestAccessControl.UseRoles({
    resource: "ProficiencyLevel",
    action: "update",
    possession: "any",
  })
  async disconnectDeveloperToolProficiencies(
    @common.Param() params: ProficiencyLevelWhereUniqueInput,
    @common.Body() body: DeveloperToolProficiencyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      developerToolProficiencies: {
        disconnect: body,
      },
    };
    await this.service.updateProficiencyLevel({
      where: params,
      data,
      select: { id: true },
    });
  }
}
